In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [ ]:
import time
import pandas as pd
import numpy as np
CITY_DATA = { 'chicago': 'chicago.csv',
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }


def get_filters():
	print('Hello! Let\'s explore some US bikeshare data!\n')
        # get user input for city (chicago, new york city, washington). HINT: Use a while loop to handle invalid inputs
	global city
	city = input("Enter the city name that you want to analyse data Chicago, New york city, Washington?\n\n").lower()
	while True:
		if city not in ["chicago", "new york city", "washington", "exit"]:
			city = input("Please check the spelling and try again. or type exit to leave the programme else Enter the city name that you want to analyse data Chicago, New york city, Washington?\n\n").lower()
		elif city == "exit":
			break
		else:
			return ('you have selected:'+ city.title()+'\n' )
			break
            
def get_month():
	global month
	month = input("Select a month from January, February, March, April, May, June or \'All\' to apply no filter\n").title()
	while True:
		if month not in ["January", "February", "March", "April", "May", "June","All"]:
			month = input("please select a month from above mentioned months in that format\n")
		else:
			return ('you have selected:' + month.title() + '\n')
			break
def get_day():
	global day
	day = input("Select any day eg.Monday or \'All\' to apply no filter\n").title()
	while True:
		if day not in ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday","All"]:
			day = input("please select a day from above mentioned days in that format\n")
		else:
			return('you have selected:' + day.title() + '\n')
			break

print(get_filters())
print(get_month())
print(get_day())
df = pd.read_csv(CITY_DATA[city])
df['Start Time'] = pd.to_datetime(df['Start Time'])
df['month'] = df['Start Time'].dt.strftime('%B')
df['day'] = df['Start Time'].dt.strftime('%A')
df['hour'] = df['Start Time'].dt.hour
if month!='All':
	df = df[df['month'] == month]   
if day!='All':
	df = df[df['day'] == day]
df.dropna()
df.head(10)

def popular_month(city):
 #get month names immediately
	popular_month = df['month'].mode()[0]
	return(popular_month)
print("The most frequent month when people take bike is "+popular_month(city)+"\n")

def popular_day(city):
#get days immediately
	popular_day = df['day'].mode()[0]
	return(popular_day)
print("The busiest day of the month when people take bike is "+popular_day(city)+"\n")

def popular_hour(city):
	popular_hour = df['hour'].mode()[0]
	return(popular_hour)
print("The Rush hour of the day is "+str(popular_hour(city))+":00hrs"+"\n")

def trip_duration2(city, month, day):
	total = np.sum(df['Trip Duration'])
	total3 = (total//3600)
	return (total3)
print("Total hours of all the trips of the day "+str(trip_duration2(city, month, day))+"hrs"+"\n")
def trip_duration1(city, month, day):
	average = np.average(df['Trip Duration'])
	average = (average/60)
	return (average)
print("Average hours of all the trips of the day "+str(trip_duration1(city, month, day))+"min"+"\n")
def popular_stations(city, month, day):
	start_station = df['Start Station'].value_counts().idxmax()
	return (start_station)
print("The popular station where people take bike -> "+popular_stations(city, month, day)+"\n")
def popular_stations2(city, month, day):
	end_station = df['End Station'].value_counts().idxmax()
	return (end_station)
print("The popular station where people drop the bike -> "+popular_stations(city, month, day)+"\n")
def popular_trip(city, month, day):
    #start_station = df['Start Station'].value_counts().index[0] #need station name, not a pd series output
    #end_station = df['End Station'].value_counts().index[0]
	df['trip'] = df['Start Station'].value_counts().idxmax()+ '-' + df['End Station'].value_counts().idxmax()
	trip = df['trip'].value_counts().idxmax()
	return(trip)
print("The busiest round trip of the day -> "+popular_trip(city, month, day)+"\n")
def users(city, month, day):
	user_types = df['User Type'].value_counts()
	return("Types of users travel "+"\n"+str(user_types)+"\n")
print(users(city, month, day))

def gender(city, month, day):
	while True:
		if city in ["washington"]:
			return("No gender column for this city")
			break
		else:
			gender = df['Gender'].value_counts()
			return("Count of different genders "+"\n"+str(gender)+"\n")
print(gender(city, month, day))

def birth_years(city, month, day):
	while True:
		if city in ["washington"]:
			return("No birth_years column for this city")
			break
		else:
			oldest = df['Birth Year'].min()
			youngest = df['Birth Year'].max()
			avg = df['Birth Year'].mean()
			return("Oldest user born in the year : "+ str(int(oldest)) +" Youngest user born in the year : "+ str(int(youngest))+" Average user birth year is : "+str(int(avg)))
print(birth_years(city, month, day))



def display_data():
	global data
	row = 0
	idx = 0
	while True:
		data = input("Do you want to see your city data enter \'yes\' or \'no\'.")
		if data not in ["yes", "no"]:
			print("Invalid input format")
		elif data == "yes":
			data = input("Enter how many sets you want to see in interger format"+"\n")
			row+=int(data)
			print(df[idx:row])
			idx=int(row)   
		elif data == "no":
			print("Bye");
			break
display_data()

Hello! Let's explore some US bikeshare data!

Enter the city name that you want to analyse data Chicago, New york city, Washington?

washington
you have selected:Washington

Select a month from January, February, March, April, May, June or 'All' to apply no filter
All
you have selected:All

Select any day eg.Monday or 'All' to apply no filter
Monday
you have selected:Monday

The most frequent month when people take bike is May

The busiest day of the month when people take bike is Monday

The Rush hour of the day is 8:00hrs

Total hours of all the trips of the day 12491.0hrs

Average hours of all the trips of the day 18.7703733108min

The popular station where people take bike -> Columbus Circle / Union Station

The popular station where people drop the bike -> Columbus Circle / Union Station

The busiest round trip of the day -> Columbus Circle / Union Station-Columbus Circle / Union Station

Types of users travel
Subscriber    30768
Customer       9162
Name: User Type, dtype: int64

No gender column for this city
No birth_years column for this city
Do you want to see your city data enter 'yes' or 'no'.yes
Enter how many sets you want to see in interger format
10
    Unnamed: 0          Start Time             End Time  Trip Duration  \
6      1594275 2017-06-19 08:41:43  2017-06-19 09:00:08       1105.429
9       327058 2017-02-20 21:12:00  2017-02-20 21:31:00       1188.090
10      854729 2017-04-17 02:50:51  2017-04-17 03:05:17        866.689
15     1592744 2017-06-19 07:46:35  2017-06-19 07:55:00        505.482
18      679837 2017-04-03 10:22:19  2017-04-03 10:26:11        231.952
22     1161275 2017-05-15 07:35:21  2017-05-15 07:49:06        825.590
25     1157984 2017-05-15 05:39:22  2017-05-15 06:02:14       1371.512
35       34042 2017-01-09 12:29:00  2017-01-09 12:48:00       1138.896
44     1416879 2017-06-05 11:32:28  2017-06-05 11:38:24        356.295
60     1503283 2017-06-12 05:53:14  2017-06-12 05:59:24        369.580

                             Start Station  \
6                  Park Rd & Holmead Pl NW
9                    17th & Corcoran St NW
10  37th & O St NW / Georgetown University
15           Metro Center / 12th & G St NW
18                       20th & Crystal Dr
22                           3rd & H St NE
25                        Lincoln Memorial
35   TJ Cmty Ctr / 2nd St & S Old Glebe Rd
44                         3rd & Elm St NW
60                 Wilson Blvd & N Uhle St

                                          End Station   User Type     month  \
6                                       8th & H St NW  Subscriber      June
9                                Lynn & 19th St North  Subscriber  February
10             37th & O St NW / Georgetown University    Customer     April
15                         North Capitol St & G Pl NE  Subscriber      June
18                                    6th & S Ball St  Subscriber     April
22                             Oklahoma Ave & D St NE  Subscriber       May
25                       Arlington Blvd & Fillmore St  Subscriber       May
35  Shirlington Transit Center / S Quincy & Randol...  Subscriber   January
44                       7th & R St NW / Shaw Library  Subscriber      June
60                            21st St N & N Pierce St  Subscriber      June

       day  hour                                               trip
6   Monday     8  Columbus Circle / Union Station-Columbus Circl...
9   Monday    21  Columbus Circle / Union Station-Columbus Circl...
10  Monday     2  Columbus Circle / Union Station-Columbus Circl...
15  Monday     7  Columbus Circle / Union Station-Columbus Circl...
18  Monday    10  Columbus Circle / Union Station-Columbus Circl...
22  Monday     7  Columbus Circle / Union Station-Columbus Circl...
25  Monday     5  Columbus Circle / Union Station-Columbus Circl...
35  Monday    12  Columbus Circle / Union Station-Columbus Circl...
44  Monday    11  Columbus Circle / Union Station-Columbus Circl...
60  Monday     5  Columbus Circle / Union Station-Columbus Circl...
Do you want to see your city data enter 'yes' or 'no'.5
Invalid input format
Do you want to see your city data enter 'yes' or 'no'.yes
Enter how many sets you want to see in interger format
6
    Unnamed: 0          Start Time             End Time  Trip Duration  \
61      440191 2017-03-06 16:56:00  2017-03-06 16:59:00        216.303
79      207988 2017-02-06 07:21:00  2017-02-06 07:29:00        477.670
84      441535 2017-03-06 18:04:00  2017-03-06 18:23:00       1170.388
86      438083 2017-03-06 11:59:00  2017-03-06 12:03:00        199.431
88      855439 2017-04-17 04:01:34  2017-04-17 04:05:53        258.932
94     1020210 2017-05-01 08:14:41  2017-05-01 08:22:19        458.207

                   Start Station                      End Station   User Type  \
61           39th & Veazey St NW             Van Ness Metro / UDC  Subscriber
79  Columbia Rd & Georgia Ave NW          Park Rd & Holmead Pl NW  Subscriber
84        Eckington Pl & Q St NE   8th & Eye St SE / Barracks Row  Subscriber
86    14th & Rhode Island Ave NW       17th & Rhode Island Ave NW  Subscriber
88                 3rd & H St NW  Columbus Circle / Union Station  Subscriber
94    14th & Rhode Island Ave NW                   18th & M St NW  Subscriber

       month     day  hour                                               trip
61     March  Monday    16  Columbus Circle / Union Station-Columbus Circl...
79  February  Monday     7  Columbus Circle / Union Station-Columbus Circl...
84     March  Monday    18  Columbus Circle / Union Station-Columbus Circl...
86     March  Monday    11  Columbus Circle / Union Station-Columbus Circl...
88     April  Monday     4  Columbus Circle / Union Station-Columbus Circl...
94       May  Monday     8  Columbus Circle / Union Station-Columbus Circl...
Do you want to see your city data enter 'yes' or 'no'.yes